language: node_js
node_js:
- '0.10'
script:
- bash ./build.sh
env:
  global:
  - secure: "VooueudR1oZjwxd8zqN4RS2E1ZfDG2+npAj91uwNG9/7zKr8w8MKAwsxvTVg2HrbHGh+OpPMITy3QNfUqRaDZA7SNG1WQaTnchPTRHc1XxDC61PCGtiDJWLefj9I98jnE+NzuxRbwQnzH40biuzgy0rIfkpVeBQBhBIt29ExGIk=" 
install:
- npm install

after_success:
- echo '===SUCCESS==='
cache:
  directories:
  - node_modules
branches:
  only:
  - master